import Head from "next/head";

const GDPR = () => {
    return ( 
        <>
        <Head>
            <title>MODERN SLAVERY STATEMENT | Sykes Seafood</title>
            <meta name="description" content="GDPR is really important to us here at Sykes Seafood. To find out the ways we are working hard to keep your personal data protected, read more here." />
        </Head>
        <section className="mx-auto px-5 container mt-5">
            <header>
                <h1 className="uppercase text-center my-6">MODERN SLAVERY STATEMENT</h1>
            </header>
            <div className="w-100 text-md flex flex-col space-y-5">
            <p>We are passionate about a cause that aims to prevent all forms of labour exploitation such as slavery, servitude and forced or compulsory labour. We know that, as a commercial organisation that supplies a good or services, it is in our aim to comply to such law. </p><p>Not only this, but we are aware of the importance of transparency within a business and
            supply chain, Sykes Seafood actively supports and welcomes the Modern Slavery Act 2015, both as a legal obligation and as a morality right.&nbsp; </p><p>All within our business, and our supply chain pro-actively monitor the management of this
            commitment and aim to work to do right in our sector. </p><p>This statement has been approved by the Board of Directors and will be reviewed and
            published, at least annually. </p><p><b>OUR BUSINESS</b></p><p>Sykes Seafoods is an online supplier of Fish &amp; Seafood. Sykes Seafoods is a trademarked subsidiary brand of Sykes Seafoods Ltd. used under license by J. Sykes &amp; Sons (Manchester) Ltd. J. Sykes &amp; Sons (Manchester) Ltd. As a company, we know that due to the complexity of the Fish and Seafood supply chain, we are driven to constantly seek further control over the sourcing of our products by ensuring that we only obtain our raw materials from the highest accredited of sources.</p><p>Our Head Office is based at 100 King Street, Knutsford, Cheshire. We also have a specialist
            Seafood processing facility in Liverpool, and Sykes London Office, where our Southern-based Sales Operatives are based. Our company houses over 104 employees split across 3 business units. All of our Sykes Seafood E-Commerce staff are based in our Sykes Head Office at 100 King Street, Knutsford, Cheshire. </p><p><b>RESPONSIBILITY </b></p><p>As a company, we are proud of the steps we have taken, continue to take, and aim to take in order to combat modern slavery and human trafficking. We know that it is in our own responsibility to ensure that we are actively aware of the potential risks of this happening within our business, and supply chain alike. We are committed to continuously improve our practice and make our supply chain aware to ensure there is clear transparency and no labour exploitation in our supply chains or under any of the Sykes bracket. </p><p>We hold an Anti-Slavery policy which reflects our commitment to the cause and mirrors our
            commitment to ethical working with high integrity throughout all of our business relationships. We do so by ensuring the implementation and enforcement of an effective system which ensures that no slavery or human trafficking issues arise within our supply chain. </p><p>Furthermore, we’ve ensured that policies such as Whistleblowing, Anti-Harassment &amp; Bullying and Anti-Corruption &amp; Bribery are in place. These policies apply to all our employees and we operate them in a strict and monitored way. </p><p><b>DUE DILIGENCE</b></p><p>As a company, we have implemented systems in place to:</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Identify and assess any potential ‘risk areas’ within our supply chains</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Monitor such ‘risk areas’ in our supply chains</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Mitigate the risk of any slavery and human trafficking issues from arising in our supply chains</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Protect Whistleblowers </p><p>Despite these structured relationships, there are times when new suppliers are necessary. To ensure that these potential new suppliers have the capability to comply to our beliefs and standards we run a series of checks throughout a number of our in-house departments. These include BRC checks, credit checks and a requested visit to the site; by one of our most experienced staff members visiting the site we are able to validate whether they are a credible supplier that will actively adhere and share our ethics and values. </p><p>We are a member of the Supplier Ethical Data Exchange (Sedex). By this, we are able to
            conduct effective risk analysis of our supply chains, resulting in further assurance of the stance of our supply chain. All of our suppliers are therefore required to register to the Sedex system, thus allowing us to review audit results. </p><p><b>SUPPLIER ADHERENCE TO OUR ETHICS &amp; VALUES</b></p><p>As an established organisation, we hold a zero-tolerance policy to slavery and human trafficking. We actively do so by having a Supply Chain Compliance Programme set in place to ensure that all in our supply chain, including contractors, actively comply with the ethics and morals that we set. This is reflected by working towards the continuous goals that we have such as the development of our credible bank of certifications including:</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; BAP (Best Aquaculture Practice)</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MSC (The Marine Stewardship Council)</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GAP (Good Aquaculture Practice)</p><p>•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ASC (Aquaculture Stewardship Council)</p><p>We also ensure to adhere to local laws for worker safety, child labour and human rights and make it imperative that all members of our supply chain do too. We care for animal health and welfare and practice horizon scanning to ensure the nature of any emerging threats to product safety, legality, quality and authenticity in any given country or origin. We aim to ensure that our supply chain consistently comply to these factors also to certify a high level of
            transparency to our supply chain. </p><p><b>TRAINING &amp; AWARENESS</b></p><p>Furthermore, we ensure a high level in understanding of the potential risks involved with labour exploitation in our supply chains and business to be available to all our staff and when necessary, our suppliers. We do so by conducting regular training with our staff and ask that our partners provide the same facility to their staff, suppliers and providers alike. </p><p>By adhering to all that has been listed, we are confident that we only receive goods and
            project goods that have come from a traceable and reliable source. We only provide goods that have been produced by workers at their own will and prevent all forms of labour exploitation on a day-to-day basis. We regularly monitor and assess our supply chain at all angles to maintain a clear transparency. We ensure to make all employees aware and train them within this sector to ensure that our business continues to work in an ethical and moral stance in all areas. </p>
            </div>            
        </section>
        </>
     );
}
 
export default GDPR;